#!/usr/bin/env node
/* eslint-disable no-console */
"use strict";

/**
 * Generate JavaScript modules with mode/fan-speed lookup tables from the
 * cloud-served Lua plugins. Reads lua-tables/*.json (produced by
 * scripts/extract-lua-tables.js) and writes one file per device type
 * under lib/midea/generated/. The hand-written device classes import
 * these instead of carrying their own copies.
 *
 * Naming convention:  T_0000_<HEX>_<VER>.json  ->  generated/<lower-hex>-maps.js
 *
 * Each output file exports:
 *   MODE_BY_INDEX  { byte: name }  -- canonical names from VALUE_MODE_*
 *   MODE_BY_NAME   { name: byte }  -- inverse
 *   FAN_BY_INDEX   { byte: name }  -- present only when the plugin defines them
 *   FAN_BY_NAME    { name: byte }
 *   META = { source, generatedAt? }    -- references the Lua filename
 *
 * For 0xAC the mode bytes in the plugin are pre-shifted (mode << 5)
 * because byte 2 of the C0/40 frame combines mode (top 3 bits) with the
 * fractional setpoint flag. We un-shift to keep the exported map
 * consistent with how every other plugin reports modes (raw 1-based
 * indices). Same with the AC fan-speed map.
 *
 * Skip any type whose plugin defines no mode constants — there's
 * nothing to generate.
 *
 * Usage:
 *   node scripts/generate-maps.js [--in lua-tables] [--out lib/midea/generated]
 */

const fs = require("fs");
const path = require("path");

// Plugin convention per type — which table holds the BYTE_MODE_*/VALUE_MODE_*
// constants, and whether the byte values are pre-shifted.
const TYPE_CONFIG = {
    A1: { table: "keyB", valueTable: "keyV", shiftBits: 0 },
    AC: { table: "keyB", valueTable: "keyV", shiftBits: 5 }, // mode = byte 2 >> 5
    FC: { table: "uptable", valueTable: "uptable", shiftBits: 4 }, // mode = byte ? >> 4
};

function invertMap(byIndex) {
    const out = {};
    for (const [k, v] of Object.entries(byIndex)) out[v] = parseInt(k, 10);
    return out;
}

function buildModeMap(tables, cfg) {
    const out = {};
    const codes = tables[cfg.table] || {};
    const labels = tables[cfg.valueTable] || {};
    for (const [k, v] of Object.entries(codes)) {
        const mm = /^BYTE_MODE_(.+)$/.exec(k);
        if (!mm || typeof v !== "number") continue;
        const tail = mm[1];
        // Find a friendly string from VALUE_MODE_<TAIL>, with a couple of
        // common singular/plural variants the cloud sometimes uses.
        const candidates = [
            `VALUE_MODE_${tail}`,
            `VALUE_MODE_${tail}S`,
            `VALUE_MODE_${tail.replace(/H$/, "HES")}`, // CLOTH → CLOTHES
        ];
        let label = null;
        for (const c of candidates) if (typeof labels[c] === "string") { label = labels[c]; break; }
        if (!label) label = tail.toLowerCase();
        const code = cfg.shiftBits ? v >> cfg.shiftBits : v;
        out[code] = label;
    }
    return out;
}

function buildFanMap(tables, cfg) {
    const out = {};
    const codes = tables[cfg.table] || {};
    const labels = tables[cfg.valueTable] || {};
    for (const [k, v] of Object.entries(codes)) {
        const mm = /^BYTE_FAN(?:SPEED)?_(.+)$/.exec(k);
        if (!mm || typeof v !== "number") continue;
        const tail = mm[1];
        const candidates = [
            `VALUE_FANSPEED_${tail}`,
            `VALUE_FAN_SPEED_${tail}`,
            `VALUE_FAN_${tail}`,
        ];
        let label = null;
        for (const c of candidates) if (typeof labels[c] === "string") { label = labels[c]; break; }
        if (!label) label = tail.toLowerCase();
        out[v] = label;
    }
    return out;
}

function emitJs(typeHex, source, modeByIndex, fanByIndex) {
    const lines = [];
    lines.push('"use strict";');
    lines.push("");
    lines.push("// AUTO-GENERATED FILE. DO NOT EDIT.");
    lines.push("// Source: " + source);
    lines.push("// Generated by scripts/generate-maps.js — re-run with `npm run sync-maps`.");
    lines.push("");
    lines.push("const MODE_BY_INDEX = " + JSON.stringify(modeByIndex, null, 4) + ";");
    lines.push("const MODE_BY_NAME = {");
    for (const [code, name] of Object.entries(modeByIndex)) {
        const safe = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
        lines.push("    " + safe + ": " + code + ",");
    }
    lines.push("};");
    if (fanByIndex && Object.keys(fanByIndex).length) {
        lines.push("");
        lines.push("const FAN_BY_INDEX = " + JSON.stringify(fanByIndex, null, 4) + ";");
        lines.push("const FAN_BY_NAME = {");
        for (const [code, name] of Object.entries(fanByIndex)) {
            const safe = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
            lines.push("    " + safe + ": " + code + ",");
        }
        lines.push("};");
        lines.push("");
        lines.push("module.exports = { MODE_BY_INDEX, MODE_BY_NAME, FAN_BY_INDEX, FAN_BY_NAME };");
    } else {
        lines.push("");
        lines.push("module.exports = { MODE_BY_INDEX, MODE_BY_NAME };");
    }
    lines.push("");
    return lines.join("\n");
}

function main() {
    const args = process.argv.slice(2);
    let inDir = "lua-tables", outDir = path.join("lib", "midea", "generated");
    for (let i = 0; i < args.length; i++) {
        if (args[i] === "--in") inDir = args[++i];
        else if (args[i] === "--out") outDir = args[++i];
        else if (args[i] === "--help" || args[i] === "-h") {
            console.log("Usage: node scripts/generate-maps.js [--in lua-tables] [--out lib/midea/generated]");
            return;
        }
    }
    if (!fs.existsSync(inDir)) { console.error(`input dir not found: ${inDir}`); process.exit(2); }
    fs.mkdirSync(outDir, { recursive: true });

    const lines = [];
    for (const f of fs.readdirSync(inDir).sort()) {
        if (!f.endsWith(".json")) continue;
        const m = /^T_0000_([0-9A-F]{2})_/.exec(f);
        if (!m) continue;
        const typeHex = m[1];
        const cfg = TYPE_CONFIG[typeHex];
        if (!cfg) {
            // Unknown convention — skip silently. The plugin probably uses
            // bare locals (B6 style) which we can't resolve to values
            // without a full Lua AST.
            lines.push(`${f}: SKIPPED (no convention configured for 0x${typeHex})`);
            continue;
        }
        const tables = JSON.parse(fs.readFileSync(path.join(inDir, f), "utf8"));
        const modes = buildModeMap(tables, cfg);
        if (!Object.keys(modes).length) {
            lines.push(`${f}: SKIPPED (no BYTE_MODE_* in ${cfg.table})`);
            continue;
        }
        const fans = buildFanMap(tables, cfg);
        const out = emitJs(typeHex, f.replace(/\.json$/, ".lua"), modes, fans);
        const outName = `${typeHex.toLowerCase()}-maps.js`;
        const outPath = path.join(outDir, outName);
        fs.writeFileSync(outPath, out, "utf8");
        const fanCount = Object.keys(fans).length;
        lines.push(`${f}: -> ${outPath}  (modes=${Object.keys(modes).length}${fanCount ? ", fans=" + fanCount : ""})`);
    }
    console.log(lines.join("\n"));
}

main();
