version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Berlin
    cooldown:
      default-days: 7
    open-pull-requests-limit: 20
    assignees:
      - TA2k
    versioning-strategy: increase
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Berlin
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    assignees:
      - TA2k
